owner: Acenox
repo: Status

sites:
  - name: Arragon
    url: https://arragon.hydeos.fr
  - name: NeoliaMC
    url: https://neoliamc.fr
  - name: Funcraft - Site web
    url: https://www.funcraft.net/fr
  - name: Forum - Funcraft
    url: https://community.funcraft.net/
  - name: Forum - Pactify
    url: https://community.ascentia.fr/
  - name: Test-Ping
    check: "tcp-ping"
    url: 45.81.80.103

status-website:
  baseUrl: /Status
  name: Status
