owner: Acenox
repo: Status

sites:
  - name: Hydeos
    url: https://hydeos.fr
  - name: Arragon
    url: https://arragon.hydeos.fr
  - name: Funcraft - Site web
    url: https://www.funcraft.net/fr
  - name: Forum - Funcraft
    url: https://community.funcraft.net/
  - name: Pactify
    url: https://www.pactify.fr/
  - name: Forum - Ascentia
    url: https://community.ascentia.fr/
  - name: Account - Ascentia
    url: https://account.ascentia.fr/
  - name: Boutique - Ascentia
    url: https://store.ascentia.fr/

status-website:
  baseUrl: /Status
  name: Status
