owner: Acenox
repo: Status

sites:
  - name: Hydeos
    url: https://hydeos.fr
  - name: Arragon
    url: https://arragon.hydeos.fr
  - name: Funcraft - Site web
    url: https://www.funcraft.net/fr
  - name: Forum - Funcraft
    url: https://community.funcraft.net/
  - name: Forum - Pactify
    url: https://community.ascentia.fr/

status-website:
  baseUrl: /Status
  name: Status
